services:
  postgres:
    image: postgres:15-alpine
    container_name: just-auth-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - just-auth-net

  backend:
    image: ghcr.io/fykio/just-auth-backend:latest
    container_name: just-auth-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_COOKIE_NAME: ${JWT_COOKIE_NAME}
      CORS_ORIGIN: ${CORS_ORIGIN}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - just-auth-net

  frontend:
    image: ghcr.io/fykio/just-auth-frontend:latest
    container_name: just-auth-frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - just-auth-net

volumes:
  postgres_data:

networks:
  just-auth-net:
    driver: bridge
